---
- name: SEP project
  hosts: 10.9.0.43
  vars:
    - stop: Start smc -stop
    - run: Start smc -start  
 
  tasks:
    block:
      - name: import role for connections with socket
        ansible.builtin.import.role:
        name: ansible-role-event-socks-tunnel

      - name: Checking for python is present
        wing_ping:
        register: answer

      - name: SEP stopped
        win_shell: "{{ stop }}"

      - name: Wait for 5 min
        communiti.windows.win_wait_for_process:
          sleep: 300

      - name: SEP started again
        win_shell: "{{ run }}"

    when: answer.ping  == 'pong' 

    rescue:
      - name: Print when python is not present
        ansible.builtin.debug:
          msg: This server doesnt have python
